language: python
sudo: true

python:
  - 3.8.5

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install -q pipenv
  - pipenv sync -d

script:
  - pipenv run flake8
  - pipenv run pytest --cov=reden

after_success:
  - pipenv run codecov
